### ISSUE TITLE
Template Trading Bot needed

### ISSUE THREAD

**Issue by vennard** [Samael404/TraderBOT_Challenge#3]
We need a template bot that connects, does one fake trade using some parameters, and then exits returning its stats back to the API that called it. Suggestion to start is to utilize the Gemini API and many Gemini Bot examples that exist.

**Comment by wiggro420** [comment]
If you can't get a Gemini sandbox account which I have been  Unable to do
then this wont-work for anyone that can't get an account.  I tried multiple
times this week to get a sandbox account add it will not allow me to get one
Josh

**Comment by vennard** [comment]
Handing over to Kevin.
